language: node_js
node_js:
  - 14

before_install:
  - npm i -g npm
  - npm i -g mocha-only-detector
  - .travis/mocha-detector.sh

jobs:
  include:
    - env:
        - TEST_PART: fullRegression

install:
  - yarn install

before_script:
  - yarn lint

script:
  - yarn c
  - .travis/test-part.sh
  - .travis/report.sh
